### ISSUE TITLE
Error: Unsupported node type ExpressionStatement

### ISSUE THREAD

**Issue by hiro5id** [ForbesLindesay/tsgen#6]
Trying to convert flow definitions from `mongodb-memory-server` npm package.  I ran command `tsgen 'node_modules/mongodb-memory-server/**/*.js.flow'` and I got the error `Unsupported node type ExpressionStatement` .  

Here is the full error:
```
   8 | import MongoInstance from './util/MongoInstance';
   9 | 
> 10 | tmp.setGracefulCleanup();
  11 | 
  12 | export type MongoMemoryServerOptsT = {
  13 |   instance: {
    at Context.getError (/Users/roberto/dev/foobook/node_modules/tsgen/lib/Context.js:90:16)
    at Object.walk [as default] (/Users/roberto/dev/foobook/node_modules/tsgen/lib/walkers/index.js:45:23)
    at /Users/roberto/dev/foobook/node_modules/tsgen/lib/index.js:30:76
    at Array.map (<anonymous>)
    at convertFile (/Users/roberto/dev/foobook/node_modules/tsgen/lib/index.js:30:22)
    at /Users/roberto/dev/foobook/node_modules/tsgen/lib/index.js:46:26
    at Array.forEach (<anonymous>)
    at Object.convertDirectory (/Users/roberto/dev/foobook/node_modules/tsgen/lib/index.js:42:34)
    at Object.<anonymous> (/Users/roberto/dev/foobook/node_modules/tsgen/lib/cli.js:20:4)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)```

**Comment by ForbesLindesay** [comment]
Thanks for reporting, should be fixed now.  N.B. tsgen is not very clever, so it won't know anything about the side effects of expression statements.

**Comment by hiro5id** [comment]
Thank you @ForbesLindesay .  Do you want me to keep reporting bugs ?   I am facing another error now in trying to generate types for the same library :)

**Comment by ForbesLindesay** [comment]
Yes, feel free to keep sending reports
